In [ ]:
path = osp.join('data', args.dataset)
img_dirs = os.listdir(path) 
seed = args.seed
np.random.seed(seed)

num_imgs = 9
n_plts = int(np.sqrt(num_imgs))

img_indices = np.random.randint(len(img_dirs),size = num_imgs)
imgs_resized = [] # containing loaded images
imgs_torch = [] # containing torch variables of images

for index in img_indices:
    img_name = osp.join(path,img_dirs[index])
    img = load_image(img_name)
    img_resized, img_torch = preprocess(img)
    imgs_resized.append(img_resized)
    imgs_torch.append(img_torch)

In [14]:
def load_image(filename):
    img = Image.open(filename).convert('RGB')
    return img
def preprocess(img):

    img = np.asarray(img.resize((224, 224))) # resize to 224 * 224 (W * H), np.asarray returns (H, W, C)
    img = transforms.Compose(
        [
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ])(img)
   
    img = img[None,:,:,:]
    return img

In [15]:
import sys
sys.path.append('../')
import os
import os.path as osp
import torch
import torch.nn as nn
import torchvision.transforms as transforms
from torch.autograd import Variable
from PIL import Image
import numpy as np
dataset = 'AachenDay'
path = osp.join('data', dataset)
img_dirs = os.listdir(path) 
img_tensor = torch.zeros(len(img_dirs),3,224,224)
for i,name in enumerate(img_dirs):
    img_path = osp.join(path,name)
    img = load_image(img_path)
    img = preprocess(img)
    img_tensor[i] = img

In [46]:
mat = torch.rand(2,512,2,2)


In [47]:
import numpy as np
mat = mat.data.numpy()
strong_activations = np.max(mat,axis=(2,3))
strong_filters = np.argmax(strong_activations,axis=1)

In [48]:
strong_filters

array([377,  36])

In [50]:
from visual.filter_extractor import *


In [1]:
import numpy as np

In [5]:
import pickle
with open('./visual/AachenDay_files/img_dirs.txt', 'rb') as img_dirs:
                pickle.load(img_dirs)

In [6]:
img_dirs

<_io.BufferedReader name='./visual/AachenDay_files/img_dirs.txt'>

In [5]:
import numpy as np 
mat = np.random.randn(5,5)
print(mat)

[[-0.44035208  0.14860178  2.04208146 -0.96398775  0.90118158]
 [-0.57906501  1.83107761  0.55693594  0.38088873 -1.58104453]
 [ 1.89423673 -0.23792438 -0.2953696  -0.34367811 -0.22116111]
 [ 0.92299091 -1.82094865 -1.91619678 -0.50655166  0.21724165]
 [ 0.61337021 -0.95293152 -0.42880754  0.90210753 -1.12523382]]


In [7]:
np.unravel_index(np.argmax(mat),(5,5))

(0, 2)

In [8]:
def get_patch_slice(img, max_index,kernel_size=15):

    
    H,W = img.shape
    h,w = max_index

    radius = (kernel_size - 1)/2

    left = w - radius
    right = w + radius + 1
    w_slice = slice( int(left*(left>=0) - (right-W+1)*(right>=W), 
                     int(right - (right-W+1)*(right>=W)) - left*(left<0)))

    up = h - radius

    down = h + radius + 1

    h_slice = slice(int(up*(up>=0) -(down-H+1)*(down>=H)), 
                    int(down - (down-H+1)*(down>=H) - up*(up<0)))

    return (h_slice, w_slice)

In [10]:
mat = np.random.randn(224,224)
get_patch_slice(mat, (0,1),kernel_size=15)

TypeError: 'float' object cannot be interpreted as an integer