In [23]:
import pickle

In [24]:
with open('matched_indices.txt','rb') as f:
    dict_ = pickle.load(f)

In [30]:
dict_['layer2']['block1']

{4: array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
         95, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127]),
 8: array([  0,  45,   2,   3,   4,   5,   6,   7,   8,   9,  74,  11,  12,
         13,  14,  15, 117,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  74,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47, 

In [35]:
import torch
import numpy as np
topK = 8
layer = 1
block = 0
filterMaxima = torch.load('figs/AachenDay_files/filter_indices_sum/filterMaxima_style0.pt')
with open('figs/AachenDay_files/filter_indices_sum/img_dirs_style0.txt', 'rb') as fb:
    img_dirs = pickle.load(fb)

maxima_values = filterMaxima['layer'+str(layer)]['block'+str(block)][0]
img_filter_indices = filterMaxima['layer'+str(layer)]['block'+str(block)][1]

maxima_h2l = np.argsort(maxima_values)[::-1][:topK]
maxima_img_idces = img_filter_indices[maxima_h2l][:,0]
maxima_filter_idces = img_filter_indices[maxima_h2l][:,1]
img_filter_indices_dict['layer'+str(layer)]['block'+str(block)] = img_filter_indices[maxima_h2l]

NameError: name 'img_filter_indices_dict' is not defined

In [33]:
idces

{'layer1': {'block0': (array([3.0792193, 3.0454497, 1.6610732, ..., 0.8530142, 2.9306633,
          3.5100827], dtype=float32),
   array([[117.,  28.],
          [136.,  20.],
          [207.,  25.],
          ...,
          [305.,  45.],
          [208.,  14.],
          [ 22.,  44.]])),
  'block1': (array([5.5975256, 3.3015804, 1.5256362, ..., 1.6683701, 3.2289991,
          1.7460722], dtype=float32),
   array([[224.,  53.],
          [  7.,  53.],
          [266.,  38.],
          ...,
          [ 73.,  48.],
          [240.,   0.],
          [311.,  59.]])),
  'block2': (array([1.5811833, 2.209377 , 4.4838963, ..., 4.6129475, 1.7087692,
          1.7801076], dtype=float32),
   array([[123.,  55.],
          [350.,  24.],
          [ 94.,  33.],
          ...,
          [293.,  60.],
          [343.,   8.],
          [266.,  39.]]))},
 'layer2': {'block0': (array([1.0469766, 2.2471437, 1.2303689, ..., 1.9825915, 1.9278902,
          1.6274593], dtype=float32),
   array([[ 74., 119.

In [44]:
import os
from utils import *
import os.path as osp
path = osp.join('data', 'AachenDay')
img_dirs = os.listdir(path)
num_samples = 350
if len(img_dirs)>=num_samples:
    rand_idces = np.random.permutation(len(img_dirs))[:num_samples]
    img_dirs = [img_dirs[idx] for idx in rand_idces]
img_tensor = torch.zeros(len(img_dirs),3,224,224)
for i,name in enumerate(img_dirs):
    img_path = osp.join(path,name)
    img = load_image(img_path)
    img = preprocess(img)
    img_tensor[i] = img

In [45]:
img_dirs[:5]

['2011-10-01_14-34-12_690.jpg',
 '2011-12-17_14-53-47_244.jpg',
 '2012-02-04_14-22-23_115.jpg',
 '2012-02-11_15-05-20_118.jpg',
 '2011-10-01_14-01-04_159.jpg']