In [41]:
import pickle

with open('./figs/AachenDay_files/maxima_full/guidedbp/style_16_img_filter_indices_dict.txt','rb') as fp:
        filter_dic = pickle.load(fp)
    

In [42]:
filter_dic

{'layer1': {'block0': array([[232.,   2.],
         [218.,   2.],
         [207.,  58.],
         [181.,  26.],
         [343.,  26.],
         [356.,   2.],
         [191.,  53.],
         [251.,   2.]]),
  'block1': array([[207.,  40.],
         [138.,   2.],
         [218.,   2.],
         [109.,   0.],
         [181.,  62.],
         [170.,   6.],
         [100.,   6.],
         [353.,  40.]]),
  'block2': array([[343.,  26.],
         [181.,  26.],
         [256.,   0.],
         [353.,  33.],
         [218.,   2.],
         [ 90.,  26.],
         [138.,   2.],
         [ 15.,   6.]])},
 'layer2': {'block0': array([[155.,  51.],
         [296.,  51.],
         [307.,  51.],
         [281.,   2.],
         [316., 109.],
         [296., 109.],
         [ 56., 109.],
         [101., 109.]]),
  'block1': array([[340.,  51.],
         [218., 109.],
         [113.,  51.],
         [ 82.,  51.],
         [ 91.,  51.],
         [ 16.,  51.],
         [193.,  51.],
         [ 73.,  51.]]),

In [35]:
import numpy as np
feat_map_label = np.zeros((3,6,2))
for i in range(feat_map_label.shape[0]):
    feat_map_label[i,:,0] = i*np.ones(feat_map_label.shape[1])
    for j in range(feat_map_label.shape[1]):
        feat_map_label[i,j,1] = j  



In [40]:
feat_map_label.reshape(-1,2)

array([[0., 0.],
       [0., 1.],
       [0., 2.],
       [0., 3.],
       [0., 4.],
       [0., 5.],
       [1., 0.],
       [1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [2., 3.],
       [2., 4.],
       [2., 5.]])

In [30]:
a[1]

array([[[-0.,  0.,  0., -2.],
        [ 1., -0., -1., -1.],
        [-0.,  2., -1.,  1.],
        [ 1.,  0.,  0., -0.]],

       [[-1., -0., -0., -1.],
        [-1.,  2., -2.,  1.],
        [-0.,  1., -1.,  2.],
        [ 0., -0., -1.,  0.]]])

In [31]:
a.reshape(-1,4,4)[2]

array([[-0.,  0.,  0., -2.],
       [ 1., -0., -1., -1.],
       [-0.,  2., -1.,  1.],
       [ 1.,  0.,  0., -0.]])